# -*- coding: utf-8 -*-
"""Test Script (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xek4Vy-Jr2nFxuS_c0ls9w2fX1tRs1co
"""

import warnings
import pandas as pd
import numpy as np
from keras.models import model_from_json
import pickle
from keras_preprocessing.sequence import pad_sequences

# loading
with open('C:\\Users\\Abduallah Hussien\\Desktop\\Graduation Project\\Text\\Models\\tokenizer.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

# loading json and model architecture


# load weights into new model
loaded_model.load_weights(
    "C:\\Users\\Abduallah Hussien\\Desktop\\Graduation Project\\Text\\Models\\Emotion_Model_lstm_text_93.h5")
print("Loaded model from disk")


loaded_model.load_weights("Emotion_Model_conv1d_gender_93.h5")


if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)


app = Flask(__name__)


json_file = open("Emotion_Model_conv1d_gender_93.json", 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)


def predict(sentence):
    dictionary = {'joy': 0, 'anger': 1, 'love': 2,
                  'sadness': 3, 'fear': 4, 'surprise': 5}
    sentence_lst = []
    sentence_lst.append(sentence)
    sentence_seq = tokenizer.texts_to_sequences(sentence_lst)
    sentence_padded = pad_sequences(sentence_seq, maxlen=80, padding='post')
    ans = np.argmax(loaded_model.predict(sentence_padded), axis=1)
    for key, val in dictionary.items():
        if (val == ans):
            print("The emotion predicted is", key)


predict(str("There are many elements in life that we find the most joy in. Some of the elements that bring me the most joy are spending time with my family, friends and helping others mostly children. The gifts and talents I have are a source of my joy. Some of those gifts and talents include my musical ability and natural connection with children."))

predict(str("I let out a sigh of frustration as I seethed in anger. When I had lent my dress to Natalia I had specifically told her to take good care of it as I hadn’t yet had a chance to wear it. It seemed that my sister hadn’t bothered about my instructions at all. If she had been standing there I would’ve wanted to shake some sense into her."))

predict(str("i scared from ghosts"))
